
classes:
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.openstack
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.glusterfs
- system.linux.system.repo.mcp.apt_mirantis.saltstack_2016_3
- service.keepalived.cluster.single
- system.glusterfs.server.cluster
- system.glusterfs.server.volume.salt_pki
- system.salt.control.virt
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.glusterfs.server.volume.backup
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.sizes.openstack
- system.salt.control.cluster.openstack_benchmark_single
#- system.salt.control.cluster.openstack_upgrade_single
- system.salt.control.cluster.stacklight_server_cluster
- system.salt.control.cluster.stacklight_log_cluster
- system.salt.control.cluster.stacklight_telemetry_cluster
- system.salt.control.sizes.stacklight
- system.salt.control.cluster.cicd_control_cluster
- cluster.vlab.cicd.gluster
- system.salt.control.sizes.cicd
- system.salt.control.cluster.ceph_mon_cluster
- system.salt.control.cluster.ceph_rgw_cluster
- system.salt.control.sizes.ceph
- cluster.vlab.infra
- cluster.vlab.infra.networking.kvm
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
    keepalived_vip_interface: br-ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: ens3
    primary_first_nic: ens4
    primary_second_nic: eth4
    salt_control_size_cpu_openstack_control: 8
    salt_control_size_ram_openstack_control: 32768
    salt_control_size_disk_profile_openstack_control: small
    salt_control_size_net_profile_openstack_control: default
    salt_control_size_cpu_openstack_database: 8
    salt_control_size_ram_openstack_database: 16384
    salt_control_size_disk_profile_openstack_database: large
    salt_control_size_net_profile_openstack_database: default
    salt_control_size_cpu_openstack_message_queue: 8
    salt_control_size_ram_openstack_message_queue: 32768
    salt_control_size_disk_profile_openstack_message_queue: small
    salt_control_size_net_profile_openstack_message_queue: default
    salt_control_size_cpu_openstack_proxy: 4
    salt_control_size_ram_openstack_proxy: 8192
    salt_control_size_disk_profile_openstack_proxy: small
    salt_control_size_net_profile_openstack_proxy: default
    salt_control_size_cpu_openstack_upgrade: 8
    salt_control_size_ram_openstack_upgrade: 16384
    salt_control_size_disk_profile_openstack_upgrade: medium
    salt_control_size_net_profile_openstack_upgrade: default
    salt_control_size_cpu_cicd_control: 8
    salt_control_size_ram_cicd_control: 12288
    salt_control_size_disk_profile_cicd_control: large
    salt_control_size_net_profile_cicd_control: default
    salt_control_size_cpu_stacklight_log: 4
    salt_control_size_ram_stacklight_log: 8192
    salt_control_size_disk_profile_stacklight_log: xxlarge
    salt_control_size_net_profile_stacklight_log: default
    salt_control_size_cpu_stacklight_server: 4
    salt_control_size_ram_stacklight_server: 8192
    salt_control_size_disk_profile_stacklight_server: small
    salt_control_size_net_profile_stacklight_server: default
    salt_control_size_cpu_stacklight_telemetry: 4
    salt_control_size_ram_stacklight_telemetry: 8192
    salt_control_size_disk_profile_stacklight_telemetry: xxlarge
    salt_control_size_net_profile_stacklight_telemetry: default
    salt_control_size_cpu_ceph_mon: 8
    salt_control_size_ram_ceph_mon: 16384
    salt_control_size_disk_profile_ceph_mon: large
    salt_control_size_net_profile_ceph_mon: default
    salt_control_size_cpu_ceph_rgw: 8
    salt_control_size_ram_ceph_rgw: 16384
    salt_control_size_disk_profile_ceph_rgw: small
    salt_control_size_net_profile_ceph_rgw: default
  salt:
    control:
      cluster:
        internal:
          node:
            bmk01:
              image: ${_param:salt_control_xenial_image}
            ctl01:
              image: ${_param:salt_control_xenial_image}
            ctl02:
              image: ${_param:salt_control_xenial_image}
            ctl03:
              image: ${_param:salt_control_xenial_image}
            dbs01:
              image: ${_param:salt_control_xenial_image}
            dbs02:
              image: ${_param:salt_control_xenial_image}
            dbs03:
              image: ${_param:salt_control_xenial_image}
            msg01:
              image: ${_param:salt_control_xenial_image}
            msg02:
              image: ${_param:salt_control_xenial_image}
            msg03:
              image: ${_param:salt_control_xenial_image}
            prx01:
              image: ${_param:salt_control_xenial_image}
            prx02:
              image: ${_param:salt_control_xenial_image}
  virt:
    nic:
      default:
        eth1:
          bridge: br-mgm
        eth0:
          bridge: br-ctl
  #   system:
  #     package:
  #       linux-image-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39-generic:
  #         version: latest
  #       linux-image-extra-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39:
  #         version: latest
  #     user:
  #       root:
  #         enabled: true
  #         name: root
  #         home: /root
  #         # Password is cloudlab, comment out, configure your SSH key bellow
  #         # and disable password auth
  #         password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./

