
classes:
- system.linux.system.repo.mcp.apt_mirantis.maas
- system.maas.region.single
- cluster.vlab.infra
parameters:
  _param:
    maas_region_port: 5240
    maas_cluster_region_port: ${_param:maas_region_port}
  maas:
    region:
      commissioning_scripts:
        00-maas-05-simplify-network-interfaces: /etc/maas/files/commisioning_scripts/00-maas-05-simplify-network-interfaces
      bind:
        host: ${_param:deploy_address}:${_param:maas_region_port}
    cluster:
      region:
        host: ${_param:deploy_address}:${_param:maas_cluster_region_port}
# linux:
#   network:
#     interface:
#       primary_interface:
#         enabled: true
#         name: ens2
#         type: eth
#         proto: static
#         netmask: ${_param:deploy_network_netmask}
#         address: ${_param:single_address}
#         gateway: ${_param:deploy_network_gateway}
#         name_servers:
#         - ${_param:dns_server01}
#         - ${_param:dns_server02}
### Sample MaaS Configuration
#  maas:
#    region:
#      subnets:
#        deploy_network:
#          cidr: 172.17.44.0/24
#          fabric: deploy_network
#          gateway_ip: 172.17.44.1
#          iprange:
#            end: 172.17.44.200
#            start: 172.17.44.92
#      fabrics:
#        deploy_network:
#          description: Fabric for deploy_network
#      machines:
#        kvm02:
#          interface:
#            mac: 00:25:90:eb:92:4a
#          power_parameters:
#            power_address: ipmi_ip
#            power_password: password
#            power_type: ipmi
#            power_user: engineer
